### ISSUE TITLE
Staring broken

### ISSUE THREAD

**Issue by bgiesing** [UnderMybrella/EternalJukebox#16]
### Description
When trying to star a song in the normal Jukebox, it says `An error occurred while starring: !` and the dev console says `Failed to load resource: the server responded with a status of 403 ()`

### Song
https://eternal.abimon.org/jukebox_go.html?id=4z1OTvKWtgxqNxzAzFda79

**Comment by UnderMybrella** [comment]
Fixed as of ce75775
