### ISSUE TITLE
one song won't play

### ISSUE THREAD

**Issue by ryankrage77** [UnderMybrella/EternalJukebox#19]
### Description
The song 'Waking Up' by Sam Houghton won't play - it gets stuck at the 'calculating pathways' stage

### Song
https://eternal.abimon.org/jukebox_go.html?id=638n8UMCLnETlm4t9wD6ze

### Additional Information
The song is over 5 minutes long - is there a length limitation, or am I just not waiting long enough?
Other songs under 5 minutes work.

**Comment by UnderMybrella** [comment]
I found the issue, but it's a bit of a weird one. I don't think it's directly related to the song itself, since the audio *does* work,  but it doesn't make the song public, and so gets in a loop, sorry!

I'll look at this more closely, though, thanks for the report.

**Comment by UnderMybrella** [comment]
Labeling this as fixed because the URL itself works, and the overarching issue seems to have been fixed on rewrite; I'm leaving this open until that goes live.

**Comment by ryankrage77** [comment]
tested & this works now.
Thanks for the fix!
