### ISSUE TITLE
Songs refuse to load, claim "Can't find info for that track"

### ISSUE THREAD

**Issue by geesi** [UnderMybrella/EternalJukebox#2]
### Description
Songs won't load. They get stuck on "fetching the analysis" for a long time before claiming "Sorry, can't find info for that track".

### Song
https://eternal.abimon.org/index.html?id=5hHudNsfZXmdgefWxAX2LG
https://eternal.abimon.org/index.html?id=54zS39oDi8p9adV0gyIzdD

### Additional Information
Song 1 is new, but song 2 has been around since 2010.

**Comment by UnderMybrella** [comment]
Known issue; there's a crucial difference between serialising/deserialising in production and development, which crashes upon trying to retrieve any new data.
Thanks for the report; unfortunately there's not much I can do over the coming weekend, but I'll try to get a fix out ASAP!

**Comment by UnderMybrella** [comment]
Should be fixed as of 6ddd940, which should be live now!
