### ISSUE TITLE
Linking to the wrong song

### ISSUE THREAD

**Issue by mlyons123** [UnderMybrella/EternalJukebox#21]
### Description
I'm trying to play "Real - Mystery Skulls Remix by Mystery Skulls " but it seems to be linking to the wrong song, and even then the song it links seems to end halfway through while the player continues to "loop" through the silence.  

### Song
https://eternal.abimon.org/jukebox_go.html?id=5r8tcUJ7zBg4sGyYTzl0ff

### Additional Information
I believe it play be playing another song by the Mystery Skulls so maybe that's where the confusion is coming from?
This is what the actual song sounds like https://www.youtube.com/watch?v=cQNjFR0Es-8

**Comment by UnderMybrella** [comment]
Sorry for not getting back to you for a while, from the sounds of things it's just a regular audio sync issue, which is unfortunate, but happens sometimes. As a work around, if you have the correct audio track (which you do seem to!) you can override the audio with the "tune" button, and it should work [like so](https://eternal.abimon.org/jukebox_go.html?id=5r8tcUJ7zBg4sGyYTzl0ff&audio=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DcQNjFR0Es-8)
