### ISSUE TITLE
Unable to load most songs

### ISSUE THREAD

**Issue by CherryLax** [UnderMybrella/EternalJukebox#22]
### Description
Nearly every song I try by Boards of Canada seems to not work, other artists too

### Song
https://eternal.abimon.org/jukebox_go.html?id=0aPrTlWUf2nmDkC9gcP5kZ

https://eternal.abimon.org/jukebox_go.html?id=6pxWghcPKRSjZPj8Ba9vpB

https://eternal.abimon.org/jukebox_go.html?id=7LY0R33pPIFr0Y64VZC9Wo

https://eternal.abimon.org/jukebox_go.html?id=7bgtelfoppWqHtwkQudvod

### Additional Information
Other artists have the same issue, hopefully those issues can be solved

**Comment by Zopieux** [comment]
Can confirm. Would it possible to upload .mp3 like before, as a fallback?

**Comment by UnderMybrella** [comment]
I'm not quite sure what the issue here is, but it seems to be an audio issue? Tuning with an audio track for the song does work, and it also seems to be fixed on the rewrite branch. I won't close this till it's merged though

**Comment by AAnoosheh** [comment]
It only works for me if you clear cache and reload each page every time (ctrl+Shift+R on Chrome)
