### ISSUE TITLE
Sorry, can't find info for that track

### ISSUE THREAD

**Issue by rebeccaj** [UnderMybrella/EternalJukebox#24]
### Description
Most songs won't load, instead give the error above. 

### Song
https://eternal.abimon.org/retro_index.html?id=34D6mvDTAPypm92EPs8Rxa
https://eternal.abimon.org/jukebox_go.html?id=4NoLnnJvVK5tpOdlNQI6RG
and many more

### Additional Information
Please fix. The Eternal Jukebox is wonderful but now it is broken.

**Comment by UnderMybrella** [comment]
Issue with disk space on the backend server, which has now been fixed. Apologies for the delay
