### ISSUE TITLE
Songs not loading

### ISSUE THREAD

**Issue by itsrajivshah** [UnderMybrella/EternalJukebox#3]
### Description
I am trying to play a song in the jukebox but it just says that it is loading the track and then the text just disappears.

### Song
https://eternal.abimon.org/jukebox_go.html?id=4q604hQba5940BbOoaenmz
https://eternal.abimon.org/jukebox_go.html?id=5fVZC9GiM4e8vu99W0Xf6J

### Additional Information
This is in Chrome but I can also reproduce the behavior in Firefox

**Comment by UnderMybrella** [comment]
Good news - the fix was nice and easy. Something broke on `youtube-dl`'s side, and a simple update fixed it. Thank you for the report! Everything should be working now, but if it isn't feel free to reopen the issue.
