### ISSUE TITLE
Jenkins host is down

### ISSUE THREAD

**Issue by Rictus** [UnderMybrella/EternalJukebox#35]
### Before
- [x] I have checked for similar issues already
- [x] My issue is not a bad syncronisation between the Spotify track and the YouTube audio (Those go [here.](https://github.com/UnderMybrella/EternalJukebox/issues/31))

### Description
Link to get the project files leads to a down hosting : https://jenkins-ci.abimon.org/job/Eternal%20Jukebox%20-%20Rewrite/
Any plan to fix this ?

### Additional Information
Got this link from the readme.

**Comment by UnderMybrella** [comment]
The Jenkins server is currently down, and it's unknown when it will return. See https://abimon.org/downtime.html for more information

For now the latest build can be found here: eternal.abimon.org/files/EternalJukebox.jar
