### ISSUE TITLE
EternalJukebox.jar needs uploading

### ISSUE THREAD

**Issue by JoySpaceCats** [UnderMybrella/EternalJukebox#40]
### Description
EternalJukebox.jar file needs uploading here or somewhere else, there is seemingly only one copy on a public server at the moment, that currently resides at eternal.abimon.org which as of writing is down (I know it'll come back later at some point).

### Additional Information
Not everyone will have the capability or requirements to compile the project from source, so a binary of it would be extremely useful to have around.

**Comment by UnderMybrella** [comment]
Apologies for the late reply! You should find that the latest builds can now be found at [Jenkins](http://jenkins-ci.abimon.org:8666/job/EternalJukebox/) or at my [website](https://abimon.org/eternal_jukebox/)
