### ISSUE TITLE
Custom mp3

### ISSUE THREAD

**Issue by arnaud512** [UnderMybrella/EternalJukebox#43]
Is it possible to add the option to upload our own mp3 file? 
Because some song are not on spotify and/or youtube.

**Comment by UnderMybrella** [comment]
From the [FAQ](https://eternal.abimon.org/faq.html):

> We use the Spotify API to break the song into beats. We play the song beat by beat, but at every beat there’s a chance that we will jump to a different part of song that happens to sound very similar to the current beat. For beat similarity we look at pitch, timbre, loudness, duration and the position of the beat within a bar. There’s a nifty visualization that shows all the possible transitions that can occur at any beat. 

At this time, no, there isn't a way to loop your own MP3 file. Your options for looping are:
* The Eternal Jukebox (this), with Spotify
* The [Infinite Jukebox](http://infinitejukebox.playlistmachinery.com/), with ***previously uploaded audio*** (So a bit of a fingers crossed)
* [Remixatron](https://github.com/drensin/Remixatron), which is a Python command line utility. This one isn't *as* flawless as the other two, but can still make some good stuff.

Will we support custom MP3 looping in the future? Maybe, maybe not. I'm looking at some integration with Remixatron, but there aren't any guarantees or promises, unfortunately. Until the day Spotify opens up analysis for custom audio, or someone remakes all the analysis (very unlikely), we're sort of at a bit of a dead end in that domain.
