### ISSUE TITLE
Unexpected end of JSON syntax error on new tracks, not on already played tracks

### ISSUE THREAD

**Issue by dgpadia** [UnderMybrella/EternalJukebox#49]
### Before
- [ Y ] I have checked for similar issues already
- [ Y ] My issue is not a bad synchronization between the Spotify track and the YouTube audio (Those go [here.](https://github.com/UnderMybrella/EternalJukebox/issues/31))

### Description
Seems like any new songs I try to open are unable to load. Once it fails (Fetching Analysis > Loading track > --Empty Space--), it then gives an error on a reload saying "Sorry, can't find info for that track: SyntaxError: Unexpected end of JSON input". Songs I've played before, popular songs, songs from the popular list, they all play fine. "New" songs, song I haven't listened to through this service yet that may be possibly not listened to by others (link is given below) are unable to play. 

### Console Logs
Failed to load resource: the server responded with a status of 401 ()
/api/profile/me:1

### Song
https://eternal.abimon.org/jukebox_go.html?id=2bqYcSSycHX7Zo6LJbA6aw

### Additional Information
None, but I'm happy to answer questions regarding this.

**Comment by UnderMybrella** [comment]
This was caused by a storage issue and has since been fixed. Thank you for the report!
