### ISSUE TITLE
Playback doesn't restart at top of song

### ISSUE THREAD

**Issue by Bendito999** [UnderMybrella/EternalJukebox#5]
### Description
When playing through a song in Google Chrome, the song stops at the end (top of the circle) of the track instead of continuing looping. The "bring it home" button was not pressed. To test, click near the top of the circle to navigate the play cursor near the loop point. Song stops when the final beat is reached.

### Song
https://eternal.abimon.org/jukebox_go.html?id=2CzipbXgzWvnoFfLUEge9O&thresh=37&audio=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DXNCQdbViQZ8&bp=48,68,9
(audio url was set in that track as Instrumental was mixed up with the normal version of the track)

Also occurs with the stock params reset 
https://eternal.abimon.org/jukebox_go.html?id=2CzipbXgzWvnoFfLUEge9O

Possibly has something to do with the spotify version and youtube audio length being different?

**Comment by UnderMybrella** [comment]
Unfortunately, I've been unable to reproduce using the two links provided. In both cases, in Firefox and Chrome, the song completed successfully. The only way I was able to reproduce was by pressing "Bring it home".

Could you try again, and if it persists check back in? If you can find any other songs that exhibit this behaviour, that would be welcome too.

**Comment by Bendito999** [comment]
Clarification: When playing normally it loops properly, but after manually seeking the track by clicking around, or using the arrow keys to change the speed, the top of the song stops playback. Load up the song and press the right arrow key multiple times (lower the branching to save time)
https://eternal.abimon.org/jukebox_go.html?id=2CzipbXgzWvnoFfLUEge9O&thresh=2&bp=0,0,0
The "Stop" button remains displaying "Stop", while if it was properly stopped, it would display "Play". 
Perhaps this is the intended operation, but it seemed strange to me. Also tested with same results on Firefox.

**Comment by UnderMybrella** [comment]
To clarify, do you mean if you manually seek *beyond the final branch?* The only way I could get it working with that link, for instance, was if it skipped over the branch, either by not "hitting" it due to an increased speed or by seeking beyond that point.
If so, that's unintentional, yes, and I'll see what I can do.

**Comment by Bendito999** [comment]
Yes, manually seeking beyond the final branch, as it is forced to follow the final branch when running automatically (which _is_ an intentional decision as the song wouldn't sound right in infinite mode after passing the top). Really the only application where the current stopping behavior is awkward is when changing speeds with the arrow keys and going past the final branch, as the song then stops at the top instead of still continuing. Top should stop song only when "bring it home" is active, else play from beginning. Really, upon further reflection, this is not very important, and I'm not sure if changing the behavior would have unintended consequences for users used to seeking towards the end to stop the song. I'll close the issue, thanks for looking into it though.
