### ISSUE TITLE
Certain songs throw an error

### ISSUE THREAD

**Issue by orfordj** [UnderMybrella/EternalJukebox#50]
### Before
- [X] I have checked for similar issues already
- [X] My issue is not a bad syncronisation between the Spotify track and the YouTube audio (Those go [here.](https://github.com/UnderMybrella/EternalJukebox/issues/31))

### Description
Getting an error saying "SyntaxError: Unexpected end of JSON"

### Console Logs
Failed to load resource: the server responded with a status of 401 ()
jukebox_go.html?id=4bQ11CjonNWB0nmw4dS5HW:1330 Could not retrieve stars: 

### Song
https://eternal.abimon.org/jukebox_go.html?id=4bQ11CjonNWB0nmw4dS5HW
Bass nipple by infected mushroom

### Additional Information
Happens with a lot of songs

**Comment by UnderMybrella** [comment]
Similar to #49, this was another storage issue, and has since been fixed. Thank you for the report!
