### ISSUE TITLE
Snav's "Doña" produces  "Internal Server Error"

### ISSUE THREAD

**Issue by rpolyano** [UnderMybrella/EternalJukebox#53]
### Description
For Snav's "Doña" I get an "Internal Server Error"

Appears to be same thing as #52 , not sure what changed to fix that issue.

### Console Logs
jukebox_go.html:1 Failed to load resource: the server responded with a status of 500 ()

### Song
https://eternalbox.dev/jukebox_go.html?id=3TmIs5VzKIpGvvkOt0Pqjf

**Comment by UnderMybrella** [comment]
Hi, thanks for the message! This is caused by a storage issue on my end, which has been resolved now.
