### ISSUE TITLE
Upload (analyze) and use own mp3 files

### ISSUE THREAD

**Issue by Wikinaut** [UnderMybrella/EternalJukebox#57]
I wish to be able to use local mp3 files, but there is currently no apparent way to do this (the InfiniteJukebox originally had a method for upload or analyzing local sound files).

**Comment by ekimekim** [comment]
For anyone arriving at this issue like I did, it's a duplicate of closed issue #43. The program relies on the Spotify API to do beat analysis so supporting custom audio is extremely difficult. The author suggests https://github.com/drensin/Remixatron as the next best option out there.

**Comment by Wikinaut** [comment]
Bravo! Thanks for that **live saving** tip!
