### ISSUE TITLE
"Resource not found"

### ISSUE THREAD

**Issue by Ezzocorbi** [UnderMybrella/EternalJukebox#71]
### Before
- [x] I have checked for similar issues already
- [x] My issue is not a bad syncronisation between the Spotify track and the YouTube audio (Those go [here.](https://github.com/UnderMybrella/EternalJukebox/issues/31))

### Description
Whenever I try accessing the page I get "Resource not found"

### Console Logs
https://pastebin.com/XBYwGdSV

### Song
None

### Additional Information
I managed to fix the last problem, now when I try to access the page I get this error:
![opera_SAS459KHAG](https://user-images.githubusercontent.com/36800339/80743811-f2ada480-8b1d-11ea-9598-33e22d41bd63.png)

I'm on Windows 10 running Java 8 221

This is my first time trying to host a website on my pc, so thank you in advance for helping a noob like me!

**Comment by UnderMybrella** [comment]
You need to download https://abimon.org/eternal_jukebox/web.zip and extract it in the same directory as the jar
