### ISSUE TITLE
Can't fix Song URL on Autocanonizer

### ISSUE THREAD

**Issue by bgiesing** [UnderMybrella/EternalJukebox#8]
### Description
Since the new site uses YouTube to play the songs, it sometimes picks the wrong one. On the main site, you can click tune to change the song to a specific link/video but on the Autocanonizer page, you can't.

### Song
This song's video has a intro and outro tacked on which messes up the timing completely so you have to change it to the "topic" video YouTube provides which is only the song.

Song on Autocanonizer with a wrong video: https://www.youtube.com/watch?v=5TGFhd8RfO8
Same Song on Eternal Jukebox with it corrected to the correct song-only video: https://eternal.abimon.org/jukebox_go.html?id=4JVuOFq4jSxwCGNV3lTRmE&audio=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DTnP-lllejZo

**Comment by UnderMybrella** [comment]
Should be fixed as of 883f3ab. It's always the smallest things that escape your notice, thanks for bringing it up!

It's a bit of a hacky fix right now, but it should work.

**Comment by bgiesing** [comment]
It does work although might I suggest changing the text copy:

![Text](https://i.imgur.com/Sw2R44V.png)

Since right now it refers to stuff only for the Eternal Jukebox.

**Comment by UnderMybrella** [comment]
Good catch, I'll fix that (among other things) when I get home. As I mentioned, it was a bit of a holdover patch, so I forgot to change the text evidently
